extern volatile uint8_t buffer_tx[2];
extern volatile uint8_t byte_tra;
extern volatile uint32_t num_conv;
extern volatile uint32_t len;
extern volatile uint8_t adc_number;
extern volatile uint8_t frequency;
extern volatile uint8_t mode; 
extern volatile uint8_t state;  
extern volatile uint8_t byte_rec;